### ISSUE TITLE
Using AWS ALB 

### ISSUE THREAD

**Issue by ryvin** [heyValdemar/xwiki-traefik-letsencrypt-docker-compose#2]
If I wanted to use this with an Application Load Balancer in AWS with certificate manager, to terminate TSL there, could that replace traefik in this stack as the reverse proxy? How might I modify this for that to work? I tried just removing traefik and currently I can log into the site using the public IP directly to the instance:8080 but when go through using the ALB I get 500 error with a healthy target group using 8080.

**Comment by ryvin** [comment]
figured out it was a configuration issue on the target group

**Comment by heyvaldemar** [comment]
hey @ryvin, I am glad that you figured this out!

You can also reach me and other IT guys on [Discord](https://discord.gg/AJQGCCBcqf). It might be faster than here.

Have a great day!

**Comment by ryvin** [comment]
thanks! and thank you very much for putting this together! In case anyone else is trying to do the same thing I forgot to mention just need to add:
ports:
      -"8080:8080"
 
 to the xwiki section in the docker-compose,yml file then the ALB with CM and lister on 443 can manage the cert and forward traffic to TG over 8080, also change the health check success codes on the TG to "200-399"
 
I really like the healthcheck and backups function you put in on the containers so went this way over what I found on the main xwiki site.
